name: farmers
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    # container: docker://iterativeai/cml:0-dvc2-base1-gpu
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1-gpu
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          # Add pfigure to the report
          echo "## Validaity results by reiong"
          cml-publish by_region.png --md >> report.md
          cml-send-comment report.md